### ISSUE TITLE
no lib 1.20.1

### ISSUE THREAD

**Issue by zc1108aaa** [Provismet/Dual-Swords#1]
### Type of Error

Crash

### Description

![image](https://github.com/Provismet/Dual-Swords/assets/155424398/77968f6f-906e-4851-a2c9-5bebec9c486b)

### Mod Version

1

### Minecraft Version

1

### Mod Loader

Fabric

### Steps to Reproduce

[latest.log](https://github.com/Provismet/Dual-Swords/files/15315581/latest.log)

**Comment by Provismet** [comment]
If you want any level of technical support, you should follow the instructions of the issue template and provide actual information.

You provided a 500 line log and a screenshot that's partilly in Chinese. What do you expect me to do with this?  
At best I can assume you didn't download [Combat+ Core](https://modrinth.com/mod/combatplus-core). It's not included in the build, you have to download it separately.
