### ISSUE TITLE
Secondary Sword Enchantments spring up often without the main enchantment that makes them function

### ISSUE THREAD

**Issue by lucibee** [Provismet/Dual-Swords#2]
### Adjustment Type

Functional tweak

### Description

Presently, if I put a sword in an enchantment table, I can get things like Riposte III or Deflection III without Parry, leading to a level 30 enchant being spent on a sword which gets no extra functionality.

**Comment by Provismet** [comment]
Which version of the mod are you playing on? This should have been resolved in the 1.1.1 version.

**Comment by lucibee** [comment]
1.1.0, in a 1.20.1 modpack

**Comment by Provismet** [comment]
Alright, it's an easy fix, so this should be done by the weekend.

**Comment by lucibee** [comment]
swag :D
