### ISSUE TITLE
Dont appear on enchanting table

### ISSUE THREAD

**Issue by Lumb3rSamur4i** [Provismet/Dual-Swords#3]
### Type of Error

Incorrect Behaviour

### Description

I have easy magic, and with other mods the enchantments appear on the enchanting table, but with this in neither trades or enchanting table appear the enchantments (sorry if it's difficult to read, im not native with english)

### Mod Version

dual-swords-2.0.0+1.21

### Minecraft Version

1.21

### Mod Loader

Fabric

### Steps to Reproduce

In my case it simply dont appear

**Comment by Provismet** [comment]
Could you tell me what other mods you're using?

**Comment by Lumb3rSamur4i** [comment]
> Could you tell me what other mods you're using?

![imagen_2024-07-17_084044024](https://github.com/user-attachments/assets/f494e949-d8af-4d33-93ce-6db7855481d2)

**Comment by Provismet** [comment]
Are you sure?

I tested with Dual Swords and Easy Magic installed, Parry and Lunge consistently appeared in the enchanting table.
![image](https://github.com/user-attachments/assets/2926e0aa-5bae-4133-a402-3d90dd0a1993)
![image](https://github.com/user-attachments/assets/30203cf9-7e37-4196-a503-dd44e96bae34)

Riposte, Deflection, Thrusting, Forceful, and Daisho do not appear in the table. Perhaps you were just unlucky?

**Comment by Lumb3rSamur4i** [comment]
I'll try again don't know if the other enchantment mod affects it

**Comment by Provismet** [comment]
Any updates on this? Do the enchantments appear for you?

**Comment by Lumb3rSamur4i** [comment]
> Any updates on this? Do the enchantments appear for you?

No luck, but found a sword with parry 3 an riposte 3 on a chest
