### ISSUE TITLE
Incorrect Animation of Shields

### ISSUE THREAD

**Issue by OliverDK75** [Provismet/Dual-Swords#4]
### Type of Error

Incorrect Behaviour

### Description

Shields arent hold upright, they are at slight angle, I dont think it was intentional but I'm mentioning it now so if it is to be fixed.

### Mod Version

dual-swords-1.1.1+1.20.1

### Minecraft Version

1.20.2

### Mod Loader

Fabric

### Steps to Reproduce

Holding a Shield or Blocking with it.

**Comment by Provismet** [comment]
Can you provide screenshots of this behaviour so I can verify it's validity.

**Comment by OliverDK75** [comment]
I've done some more investigating, it was another Mod which was causing this. Sorry for the inconvenience.
