### ISSUE TITLE
Better combat and parry rendering incompatabilty

### ISSUE THREAD

**Issue by redtardis12** [Provismet/Dual-Swords#6]
### Type of Error

Incorrect Behaviour

### Mod List

- Better combat
- Combat+ core
- Dual Swords

### Description

When using Parry enchantment, the sword model does not revert right-side down when attacking with Better Combat animation.
 
It's not really a huge issue, as everything works just fine. It's just that BC's animations look a bit silly. I don't even know if it is possible to fix as Better combat triggers attack action differently i guess.

I was just thinhking about adding a config option for disabling the upside-down render for parry? Maybe even as a client-side option.

### Mod Version

1.1.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Steps to Reproduce

1. Install better combat
2. Enchant any weapon with Parry
3. Attack with the weapon

**Comment by Provismet** [comment]
This specific issue is relating to Better Combat's animation system, which presumably overhauls large parts of vanilla's animation system. It is _theoretically_ possible to fix this, but doing so potentially requires depending on Better Combat in this codebase, or attempting to reverse-engineer Better Combat's animations; neither of these options are viable.

More generally though, Dual Swords is part of the Combat+ ecosystem. Combat+ as a whole should be assumed to have various with Better Combat as the two exist with very different aims.  
- Better Combat changes a lot about the combat system in a very vanilla-unfriendly way.
- Combat+ aims to be as vanilla+ / vanilla-friendly as possible.

In general, compatibility fixes for Better Combat will not be worked on.
